# Generated by Django 4.1.1 on 2022-10-21 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_fuel_type_alter_car_is_feautered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
